name: daily-hypem-spotify
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://hypem-spotify-ebon.vercel.app/api/daily?key=${{ secrets.SECRET }}' \
